# Generated by Django 5.2.6 on 2025-09-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Shoes'), ('ball', 'Ball'), ('accessory', 'Accessory'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
