# Generated by Django 5.2.6 on 2025-09-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('apparel', 'Apparel'), ('accessories', 'Accessories'), ('shoes', 'Shoes')], default='apparel', max_length=20),
        ),
    ]
